ferret:
  plus: 2
  plus_url: https://tool.ferret-plus.com/
  media: 4
  media_url: https://ferret-plus.com
  marketers_store: 6
  marketers_store_url: https://mkst.ferret-plus.com
  contents_writing: 7
  contents_writing_url: https://cw.ferret-plus.com
